---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-www
  namespace: webserver
  labels:
    app: nginx
    backup-include: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-logs
  namespace: webserver
  labels:
    app: nginx
    # backup-include: "false"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: webserver
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-www
        - mountPath: /var/log/nginx
          name: nginx-logs
        ports:
        - containerPort: 80
      volumes:
      - name: nginx-www
        persistentVolumeClaim:
          claimName: nginx-www
      - name: nginx-logs
        persistentVolumeClaim:
          claimName: nginx-logs

